/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Decar1216
 */
public class MultiChoiceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form MultiChoiceQuiz
     */
    public MultiChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        csqlbl = new javax.swing.JLabel();
        instructionslbl = new javax.swing.JLabel();
        q1lbl = new javax.swing.JLabel();
        q2lbl = new javax.swing.JLabel();
        q3lbl = new javax.swing.JLabel();
        q4lbl = new javax.swing.JLabel();
        q5lbl = new javax.swing.JLabel();
        answersbtn = new javax.swing.JButton();
        a1lbl = new javax.swing.JLabel();
        b1lbl = new javax.swing.JLabel();
        c1lbl = new javax.swing.JLabel();
        d1lbl = new javax.swing.JLabel();
        q1txt = new javax.swing.JTextField();
        scorelbl = new javax.swing.JLabel();
        q2txt = new javax.swing.JTextField();
        q3txt = new javax.swing.JTextField();
        q5txt = new javax.swing.JTextField();
        q4txt = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        Percentlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        csqlbl.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        csqlbl.setText("BioChemistry quiz");

        instructionslbl.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        instructionslbl.setText("please select one letter per question");

        q1lbl.setText("Question 1. What is protein denaturation");

        q2lbl.setText("Question 2. what ratio is used in carbohydrates");

        q3lbl.setText("Question 3. what type of bonds do fatty acids form");

        q4lbl.setText("Question 4. how does the human body regulate enzyme activity");

        q5lbl.setText("Question 5. what kind of bond forms between two cysteines");

        answersbtn.setText("Check answers");
        answersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answersbtnActionPerformed(evt);
            }
        });

        a1lbl.setText("a) the creation of  immunoglobulins and antibodies ");

        b1lbl.setText("b) the Transportation of nutrients");

        c1lbl.setText("c) Breaking of tertiary structure bonds");

        d1lbl.setText("d) the process of storing nutrients");

        q5txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5txtActionPerformed(evt);
            }
        });

        q4txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4txtActionPerformed(evt);
            }
        });

        a2.setText("a) 1:3:5");

        b2.setText("b) 3:2:9");

        c2.setText("c) 4:2:5");

        d2.setText("d) 1:2:1");

        a3.setText("a) Ester linkages");

        b3.setText("b)polypeptide");

        c3.setText("c) triglycerides");

        d3.setText("d) Polar Covalent");

        a4.setText("a) Feedback regulation ");

        b4.setText("b) Feedback inhibition");

        c4.setText("c) Enzyme kinetics ");

        d4.setText("d) Competitive inhibitor ");

        a5.setText("a) Disulfide bridge");

        b5.setText("b) resulfide bridge");

        c5.setText("c) Globular Bonds");

        d5.setText("d) Saturated Bonds");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q2lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(385, 385, 385))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d1lbl)
                            .addComponent(c1lbl)
                            .addComponent(b1lbl)
                            .addComponent(a1lbl))
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(q4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a4)
                                .addComponent(b4)
                                .addComponent(a5)
                                .addComponent(b5)
                                .addComponent(c5)
                                .addComponent(d5)
                                .addComponent(d4))
                            .addComponent(q4lbl)
                            .addComponent(c4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(q3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d2)
                            .addComponent(c2)
                            .addComponent(a2)
                            .addComponent(q1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2)
                            .addComponent(b3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c3)
                                    .addComponent(d3))
                                .addGap(266, 266, 266)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answersbtn)
                                    .addComponent(Percentlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(a3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scorelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(q1lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(q2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(q3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(csqlbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(instructionslbl)))
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(csqlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionslbl)
                .addGap(18, 18, 18)
                .addComponent(q1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(a1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q2lbl)
                        .addGap(1, 1, 1)
                        .addComponent(a2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(a4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4)
                        .addGap(11, 11, 11)
                        .addComponent(d4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(q5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(q3lbl)
                        .addGap(13, 13, 13)
                        .addComponent(a3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3)
                        .addGap(9, 9, 9)
                        .addComponent(c3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(scorelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Percentlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3)
                    .addComponent(answersbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answersbtnActionPerformed
    int answersright=0;
    int percent=0;
    String a1;
    String a2;
    String a3;
    String a4;
    String a5;
    
    
    {  a1=q1txt.getText();
     if (a1.equals ("c"))
         answersright=answersright+1;
     
     else if (a1.equals("C"))
         answersright=answersright+1;

     else
         answersright=answersright;}
     
     
     {a2=q2txt.getText();
     if (a2.equals ("d"))
         answersright=answersright+1;
     else if (a2.equals("D"))
         answersright=answersright+1;

     else
         answersright=answersright;}
       
     {a3=q3txt.getText();
     if (a3.equals ("a"))
         answersright=answersright+1;
     else if (a3.equals("A"))
         answersright=answersright+1;
     else
         answersright=answersright;}
     
     {a4=q4txt.getText();
     if (a4.equals ("B"))
         answersright=answersright+1;
     else if (a4.equals("B"))
         answersright=answersright+1;

     else
         answersright=answersright;}
     
     {a5=q5txt.getText();
     if (a5.equals ("A"))
         answersright=answersright+1;
     else if (a5.equals("A"))
         answersright=answersright+1;

     else
         answersright=answersright;}
     
     if (answersright>=4)
     scorelbl.setText("you got "+answersright+"/5 congratulations");
     
     else
         scorelbl.setText("you got "+answersright+"/5 I Know you can do better if you try again");
     
   percent=answersright*100/5;
   Percentlbl.setText("you got "+percent);
     
    }//GEN-LAST:event_answersbtnActionPerformed

    private void q4txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4txtActionPerformed

    private void q5txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Percentlbl;
    private javax.swing.JLabel a1lbl;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JButton answersbtn;
    private javax.swing.JLabel b1lbl;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel c1lbl;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel csqlbl;
    private javax.swing.JLabel d1lbl;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel instructionslbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel q1lbl;
    private javax.swing.JTextField q1txt;
    private javax.swing.JLabel q2lbl;
    private javax.swing.JTextField q2txt;
    private javax.swing.JLabel q3lbl;
    private javax.swing.JTextField q3txt;
    private javax.swing.JLabel q4lbl;
    private javax.swing.JTextField q4txt;
    private javax.swing.JLabel q5lbl;
    private javax.swing.JTextField q5txt;
    private javax.swing.JLabel scorelbl;
    // End of variables declaration//GEN-END:variables
}
